version: '3'
services:
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev
  server:
    build: .
    volumes:
      - .:/home/app/geode
    ports:
      - '8000:8000'
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://admin:password@postgres/dev
    depends_on:
      - postgres
    command: ['yarn', 'boot']
